### PR TITLE
added edit commands

### PR DESCRIPTION
**Pull request by ConnorDoesDev**
seemed kinda cool so, yeah

### CODE REVIEW

**Review by pinnouse — CHANGES_REQUESTED** [review]
Would want to make sure the bot isn't responding to other bots changing messages.
I'm not sure how often in the real world people would actually use this feature either

**Comment by pinnouse** [comment]
Also consider making PRs to the update-deps branch since master is an outdated code base

**Comment by ConnorDoesDev** [comment]
> Would want to make sure the bot isn't responding to other bots changing messages.
> 
> I'm not sure how often in the real world people would actually use this feature either

Oops! Thanks, I literally forgot that 😅

**Comment by ConnorDoesDev** [comment]
> Also consider making PRs to the update-deps branch since master is an outdated code base

Alrightys! Will do

**Comment by pinnouse** [comment]
I guess closing since it was reopened as another PR

**Pull request closed without merging**
